robot_joints:
  arm_joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint
  tool_joints:
    - bh_j11_joint
    - bh_j12_joint
    - bh_j22_joint
    - bh_j32_joint